version: "3"

services:
  # mysqldb:
  #   image: mysql:latest
  #   container_name: mysql-con
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=bluedb
  #     - MYSQL_PASSWORD=password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10
  #   networks:
  #     - internalnet
  #   restart: unless-stopped

  node-api-A:
    image: node_api_image
    container_name: nodeApiA-con
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_USER=bluekiwi
      - DB_PASS=kiwi@1117734644
      - DB_NAME=bluedb
      - SERVER_PORT=3000
      - JWT_SECRET=6708294
      - TRANSPORTER_EMAIL_PASS=Bb6708294
      - SERVER_EMAIL=invite.me.application@hotmail.com
      - SMTP_NAME=bluekiwiapp.com
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   mysqldb:
    #     condition: service_healthy
    # networks:
    #   - internalnet
    restart: unless-stopped

  node-api-B:
    image: node_api_image
    container_name: nodeApiB-con
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_USER=bluekiwi
      - DB_PASS=kiwi@1117734644
      - DB_NAME=bluedb
      - SERVER_PORT=3001
      - JWT_SECRET=6708294
      - TRANSPORTER_EMAIL_PASS=Bb6708294
      - SERVER_EMAIL=invite.me.application@hotmail.com
      - SMTP_NAME=bluekiwiapp.com
    # ports:
    #   - "3001:3001"
    # depends_on:
    #   mysqldb:
    #     condition: service_healthy
    # networks:
    #   - internalnet
    restart: unless-stopped

  node-auth:
    image: node_auth_image
    container_name: nodeAuth-con
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_USER=bluekiwi
      - DB_PASS=kiwi@1117734644
      - DB_NAME=bluedb
      - SERVER_PORT=3002
      - JWT_SECRET=6708294
      - TRANSPORTER_EMAIL_PASS=Bb6708294
      - SERVER_EMAIL=invite.me.application@hotmail.com
      - SMTP_NAME=bluekiwiapp.com
    # ports:
    #   - "3002:3002"
    # depends_on:
    #   mysqldb:
    #     condition: service_healthy
    # networks:
    #   - internalnet
    restart: unless-stopped
# volumes:
#   db:
# networks:
#   internalnet:
